import { closeBrowser, openApp } from "./browser.ts";
import { testPng } from "./helpers.ts";
const t = await openApp({}, { width: 390, height: 780 });
t.app.store.updateSettings({ replyDebounceSeconds: 0.2, typingBaseMs: 50, typingPerCharMs: 1 });
await t.page.reload();
await t.page.waitForFunction("eventSource && eventSource.readyState === 1");
t.fake.replies.push({ content: "A golden retriever puppy asleep on a blue couch, one ear flopped over its eyes. A half-eaten sock is next to it. Text on a sticky note on the wall reads \"NO SOCKS\".", delayMs: 800 }, { content: "OMG<cht>the NO SOCKS sign with the sock right there 😭" });
await t.page.setInputFiles("#attach-input", { name: "dog.png", mimeType: "image/png", buffer: testPng(800, 600) });
await t.page.waitForSelector(".composer-attachment img");
await t.page.fill("#composer-input", "look who did it again");
await t.page.screenshot({ path: "/tmp/claude-0/-home-user-kitsikai-/de28062c-a5a4-5186-90e9-17a1bcd98335/scratchpad/img-compose.png" });
await t.page.keyboard.press("Enter");
await t.page.waitForSelector('.image-seen[data-status="reading"]');
await t.page.screenshot({ path: "/tmp/claude-0/-home-user-kitsikai-/de28062c-a5a4-5186-90e9-17a1bcd98335/scratchpad/img-reading.png" });
await t.page.waitForSelector('.message[data-author="kitsikai"]:has-text("NO SOCKS sign")');
await t.page.waitForTimeout(300);
await t.page.screenshot({ path: "/tmp/claude-0/-home-user-kitsikai-/de28062c-a5a4-5186-90e9-17a1bcd98335/scratchpad/img-read.png" });
console.log(JSON.stringify(t.fake.requests.map((r) => r.messages.map((m) => typeof m.content === "string" ? m.content.slice(-200) : "[parts]")), null, 1));
await t.close();
await closeBrowser();
